# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-tutorial',
                'doc_host': 'https://WillBriggs-SI.github.io',
                'git_url': 'https://github.com/WillBriggs-SI/nbdev-tutorial',
                'lib_path': 'nbdev_tutorial'},
  'syms': { 'nbdev_tutorial.core': {'nbdev_tutorial.core.foo': ('core.html#foo', 'nbdev_tutorial/core.py')},
            'nbdev_tutorial.testing': { 'nbdev_tutorial.testing.foo': ('core.html#foo', 'nbdev_tutorial/testing.py'),
                                        'nbdev_tutorial.testing.say_hi': ('core.html#say_hi', 'nbdev_tutorial/testing.py')}}}
