# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'say_hi', 'HiSayer']

# %% ../nbs/00_core.ipynb 4
def foo(): pass

# %% ../nbs/00_core.ipynb 6
def say_hi(to):
    "Say hi to somebody"
    return f'Hi {to}!'

# %% ../nbs/00_core.ipynb 14
class HiSayer:
    "Say hi to `to` using `say_hi`"
    def __init__(self, to): self.to = to
        
    def say(self):
        "do the saying"
        return say_hi(self.to)
